---
title: "Analyze Pi Estimations"
output: html_notebook
---

```{r setup}
# Packages ----
library(tidyverse)
```


This notebook analyzes and visualizes the output from
[`estimate-pi.R`](estimate-pi.R) that is created via Launcher and local
background jobs.

## Read in Pi estimation results
```{r}
pi_files <- fs::dir_ls(here::here("programmatic-job", "output"), regexp = "*.rds$")

pi_results <- map_df(pi_files, ~{
  read_rds(.x) %>% 
    as_tibble(.name_repair = ~make.names(., unique = TRUE)) %>% 
    rename("Y" = "X.1") %>% 
    mutate(pi_estimate = cumsum((X^2 + Y^2) <= 1)/row_number() * 4, 
           file = .x)
})
```

## Simple analysis
Number of rows in each output file
```{r}
pi_results %>% 
  count(file)
```

Estimate Pi using the results in each output file
```{r}
pi_results %>% 
  group_by(file) %>%
  filter(row_number() == max(row_number()))

pi_results %>% 
  group_by(file) %>%
  summarise(pi_estimate = mean((X^2 + Y^2) <= 1) * 4)
```

## Visualization
```{r}
pi_results %>% 
  group_by(file) %>% 
  mutate(obs = row_number() * 25) %>% 
  ggplot(aes(x = obs, y = pi_estimate, group = file)) +
  geom_hline(yintercept = pi, col = "red") +
  geom_point(alpha = .1, shape = 20) +
  geom_line(alpha = .4) +
  theme_minimal() +
  scale_x_continuous(labels = scales::comma) +
  labs(title = "Pi Estimate Convergance",
       y = "Pi Estimate",
       x = "Observation")
```

